---
- hosts: PRD_APACHE
  tasks:
    - name: run apache install
      apt:
        name: apache2
        state: present
    - name: create a repo
      ansible.builtin.file:
        path: /root/test
        state: directory
        mode: "0755"
    - name: create file
      ansible.builtin.file:
        path: /root/test/test_FileModule.txt
        state: touch
        mode: "0755"
    - name: delete index.html
      file:
        path: /var/www/html/index.html
        state: absent
    - name: Template for apache index
      ansible.builtin.template:
        src: template/index.html
        dest: /var/www/html/index.html
    - name: Gather Facts check
      file:
        path: /root/{{path_file}}
        state: touch
    - name: change motd
      copy : 
        src: motd
        dest: /etc/motd
        mode: "0644"
